apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: harbor-repo.vmware.com/vac_vmware_it/containers/photon-4/kafka:3.6.1-photon-4-r27
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://sentry-kafka:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: CONFLUENT_SUPPORT_METRICS_ENABLE
          value: "false"
        - name: KAFKA_LOG4J_LOGGERS
          value: "kafka.cluster=WARN,kafka.controller=WARN,kafka.coordinator=WARN,kafka.log=WARN,kafka.server=WARN,kafka.zookeeper=WARN,state.change.logger=WARN"
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: "WARN"
        - name: KAFKA_TOOLS_LOG4J_LOGLEVEL
          value: "WARN"
---
apiVersion: v1
kind: Service
metadata:
  name: sentry-kafka
spec:
  selector:
    app: kafka
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9092
    targetPort: 9092